export const ENDPOINT_UPLOAD_FILES = '/uploadFiles';
export const ENDPOINT_GET_RECORDS='/getRecords';
export const ENDPOINT_GET_RECORD="/getRecord";
export const ENDPOINT_GET_LAST_RECORD="/getLastRecord";
export const ENDPOINT_GET_TRANSCRIPT="/getTranscript";
export const ENDPOINT_STREAM_RECORD="/streamRecord";
export const ENDPOINT_CONVERT_ALL_RECORDS="/convertAllRecords";
export const ENDPOINT_CONVERT_RECORD="/convertRecord";
export const ENDPOINT_LOGIN="/login";
export const ENDPOINT_UPDATE_TRANSCRIPT="/updateTranscript";
export const ENDPOINT_GET_SUBRECORDS_BY_ID="/getSubRecordsById";
export const ENDPOINT_CREATE_VTT_BY_RECORD_ID="/createVttFileByRecordId";
export const ENDPOINT_CREATE_VTT_BY_MEETING_ID="/createVttFileByMeetingId"
export const ENDPOINT_DOWNLOAD_RECORD="/downloadRecord";
export const ENDPOINT_GET_TRANSCRIPT_LIST_BY_MEETINGID ="/getTranscriptListByMeetingId";
export const ENDPOINT_DELETE_RECORD="/deleteRecord";    
export const ENDPOINT_GET_RECORDS_BY_MEETING_ID= "/getRecordsByMeetingId"
export const ENDPOINT_UPDATE_RECORD_FLAG="/updateRecordingFlag";
export const ENDPOINT_GET_LANGUAGE_LIST="/getLanguageList";
export const ENDPOINT_SELECT_LANGUAGE="/select_language";